services:
  app:
    build: . 
    container_name: mantenimiento
    volumes:
      - ./app:/var/www/html/app
      - ./config/prod/virtualhosts/films-alberto-despliegue-mantenimiento.chickenkiller.com.conf:/etc/apache2/sites-enabled/films-alberto-despliegue-mantenimiento.chickenkiller.com.conf
    ports:
      - "80:80"