services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: mantenimiento-dev
    volumes:
      - ./app:/var/www/html/app
      - ./config/dev/virtualhosts/films-alberto-despliegue-mantenimiento-dev.com.conf:/etc/apache2/sites-enabled/films-alberto-despliegue-mantenimiento-dev.com.conf
    ports:
      - "8081:80"